blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

# Para los archivos medias
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    # app home
    path('', include('app.home.urls')),

    # app user
    path('', include('app.user.urls')),

    # app entradas
    path('', include('app.entrada.urls')),

    # app favoritos
    path('', include('app.favoritos.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/app/home/models.py
from django.db import models


# INSTALLA  django model utilis
# pip install django-model-utils
# apps terceros
# con el timeStampedModel ya nos tra fecha de creacion y de actulizacion y los models
from model_utils.models import TimeStampedModel

# Create your models here.

"""
con este modelo se envian varios contextos al home
title es el titulo de la pagina enviada al home
description : es la descrpcion del contenido debajo del titulo
about_title: es el titulo de nostros
about_text: donde escribimo el mas sobre notros
contac_email: correo donde nos contactan desde home se muestra
phone: numero de telefono que se muestra desde el home
"""


class Home(TimeStampedModel):
    """ Model para datos de la pantalla home  """
    title = models.CharField('Nombre', max_length=30)
    description = models.TextField()
    about_title = models.CharField('Titulo Nosotros', max_length=50)
    about_text = models.TextField()
    contact_email = models.EmailField(
        'email de contacto', blank=True, null=True)
    phone = models.CharField('Telefono contacto', max_length=20)

    class Meta:
        verbose_name = 'Pagina Principal'

    def __str__(self):
        return self.title


# este modelo es un campo de solo email para la suscrpcion de la pagina desde el home
class Suscribers(TimeStampedModel):
    """ Suscripciones """

    email = models.EmailField()

    class Meta:
        verbose_name = 'Suscriptor'

    def __str__(self):
        return self.email


# este modelo se utiliza para el formulario para que te contacte ubicado en home
class Contact(TimeStampedModel):
    """ Formulario de Contacto """

    full_name = models.CharField('Nombres', max_length=60)
    email = models.EmailField()
    messagge = models.TextField()

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Mensajes'

    def __str__(self):
        return self.full_name

blog/app/user/forms.py
# para realizar formularios personalizados
from django import forms

# Importaciones para autenticacion de usuario
from django.contrib.auth import authenticate

# validaciones para la contraseña
from django.contrib.auth.password_validation import MinimumLengthValidator, NumericPasswordValidator, CommonPasswordValidator


from django.core.exceptions import ValidationError

# modelo user
from .models import User


class validator_password(forms.Form):

    pass


class RegisterForms(forms.ModelForm):

    password1 = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Contraseña1'}))
    password2 = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Contraseña2'}))

    class Meta:
        model = User
        fields = ['email', 'full_name', 'ocupation', 'genero', 'date_birth']

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'full_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre Completo'}),
            'ocupation': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ocupacion'}),
            'genero': forms.Select(attrs={'class': 'form-control', 'placeholder': ''}),
            'date_birth': forms.DateInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': 'Fecha de nacimiento'})
        }

        labels = {
            'email': '', 'full_name': '', 'ocupation': '', 'genero': '', 'date_birth': ''
        }

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2:
            try:
                validator_password(password1)
                validator_password(password2)
                CommonPasswordValidator().validate(password1)
                NumericPasswordValidator().validate(password1)
            except forms.ValidationError as e:
                msg = f'La contraseña no es valida , {",".join(e)}'
                self.add_error('password1', msg)
            if password1 != password2:
                self.add_error(
                    'password2', 'Las contraseñas no coinciden ')

        return password1


class LoginForm(forms.Form):

    email = forms.CharField(label='', widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Email'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Contraseña'}))

    def clean(self):

        ususario = authenticate(
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password']
        )

        if not ususario:
            raise forms.ValidationError(
                "El correo o la contraseña son incorrectas")

        return super().clean()


# Formulario para el código de confirmación del registro del usuario
class CodeRegistroForm(forms.Form):

    # aqui creo lo que mostrare en formulario
    codigoregistro = forms.CharField(label='', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Ingresa codigo'}))

    """__init__(): Se utiliza para inicializar el formulario. 
    Aquí se pasa el pk como argumento y se guarda en self.id_user"""

    def __init__(self, pk, *args, **kwargs):
        self.id_user = pk
        super(CodeRegistroForm, self).__init__(*args, **kwargs)

    def clean_codigoregistro(self):
        codigo = self.cleaned_data['codigoregistro']

        if len(codigo) != 6:
            raise ValidationError(
                f'El codigo es incorrecto, solo tiene {len(codigo)} y debe ser 6 ')

        if not User.objects.codigo_validacio(self.id_user, codigo):
            raise forms.ValidationError('El codigo es incorrecto...')


class UpdatePasswordForm(forms.Form):

    password1 = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Contraseña actual'}))
    password2 = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Contraseña nueva'}))

blog/templates/includes/footer.html
{% block footer %}
{% load static %}
<!-- Footer-->
<footer class="bg-dark text-white py-3">
    <div class="container text-center">
        <div class="row">
            <div class="col-8 ps-5">
                <h5>Contacto</h5>
                <form  class="m-auto p-2" action="{% url 'add-suscription-contac' %}" method="post">{% csrf_token %}

                    <div class="row">
                        <div class=" col-6  mb-3">
                            <input class="form-control" type="text" name="full_name" id="id_full_name" placeholder="Nombre:" aria-label="default input example">
                        </div>
    
                        <div class="col-6">    
                            <input class="form-control" placeholder="Email:" type="email" name="email" id="id_email">
                        </div>
                    </div>

                    <br>
                    <textarea class="form-control" id="id_messagge" name="messagge" rows="3" placeholder="Mensaje"></textarea>
                    <button class="btn btn-primary mt-3" type="submit">Enviar</button>
                </form>
            </div>

            <!-- Card de mi-->
            <div class="col-md-4 pt-3">
                <div  style="width: 18rem;">
                    <img src="{% static 'img/fami.jpg' %}" class="card-img-top rounded-circle" style="height: 100px; width: 100px;"  alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Mi pagina principal.</h5>
                        <p class="card-text">Desarrolador backend</p>
                        <a href="#" class="btn btn-primary">Ir a mi pagina principal</a>
                    </div>
                </div>
            </div>
        </div><!-- Fin de la fila -->
        <p class="mt-4">© {% now "Y" %} Tu Empresa. Todos los derechos reservados.</p>
        <p>Otra forma de contactar</p>
        <p>Numero: {{phone}}</p> <p>Correo: {{correo}}</p>

    </div><!-- Fin del contenedor -->
</footer>
{% endblock %}

blog/templates/includes/top-menu.html
{% extends "home/base.html" %}

{% block content %}
     
    <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">Django Blog </a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link {% if request.path == '/' %}active{% endif %} " href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link {% if request.path == '/entradas' %}active{% endif %} " href="{% url 'entradas'%}">Blog</a></li>
                        {% if request.user.is_active%}
                        <li class="nav-item"><a class="nav-link {% if request.path == '/logout' %}active{% endif %} " href="{% url 'profiles'%}">Perfil</a></li>
                           <li class="nav-item"><a class="nav-link {% if request.path == '/password-change' %}active{% endif %} " href="{% url 'password-change'%}">Cambia contraseña</a></li>
                           <li class="nav-item"><a class="nav-link {% if request.path == '/logout' %}active{% endif %} " href="{% url 'logout'%}">Salir</a></li>
                           
                        {% else %}                           
                        <li class="nav-item"><a class="nav-link " aria-current="page" href="{% url 'login' %}">Acceder</a></li>
                        {% endif %}  
                    </ul>
                </div>
            </div>
        </nav>
{% endblock %}